# Generated by Django 4.2.6 on 2023-11-10 17:09

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='mediafiles', validators=[main.validators.file_size]),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
